Get-VM 	CASSRV13	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	CASSRV13	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	CASSRV13	| Get-NetworkAdapter -Name 	'Network adapter 4'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	CASSRV14	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	CASSRV14	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	CASSRV14	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	DNSSRV24	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $false	 -confirm:$false
Get-VM 	DNSSRV24	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $false	 -confirm:$false
Get-VM 	DNSSRV24	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $true	 -confirm:$false
Get-VM 	DNSSRV25	| Get-NetworkAdapter -Name 	'Network adapter 4'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $false	 -confirm:$false
Get-VM 	DNSSRV25	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $false	 -confirm:$false
Get-VM 	DNSSRV25	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1114_PROD_1	-StartConnected	 $true	 -confirm:$false
Get-VM 	MBXSRV12	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	MBXSRV12	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	MBXSRV12	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	PIXEON-VA	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	PIXEON-VA	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJDB11	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJDB11	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJFS01	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJFS01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJMBX01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJMBX01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJMBX01	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTLN01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTLN01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTLN04	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTLN04	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTLN05	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTLN05	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTLN06	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTLN06	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTLN07	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTLN07	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS02	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS02	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS03	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS03	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS05	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS05	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS06	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS06	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS07	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS07	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS08	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS08	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS09	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS09	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS10	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS10	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS11	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS11	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS12_Clone	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS12_Clone	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS13	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS13	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS14	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS14	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS15	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS15	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS16	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS16	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS17	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS17	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS18	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS18	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS19	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS19	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS20	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS20	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS21	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS21	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS22	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS22	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS23	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS23	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTS24	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTS24	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSAB01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSAB01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSAB02	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSAB02	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSAUT01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSAUT01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSINT01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSINT01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSMX01	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSMX01	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSMX01	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSMX02	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSMX02	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJTSWPD06	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJTSWPD06	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJWBI01.UREMH.LOCAL	| Get-NetworkAdapter -Name 	'Network adapter 6'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
Get-VM 	UNIRJWBI01.UREMH.LOCAL	| Get-NetworkAdapter -Name 	'Network adapter 7'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJWBI01.UREMH.LOCAL	| Get-NetworkAdapter -Name 	'Network adapter 8'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJWPA03	| Get-NetworkAdapter -Name 	'Network adapter 1'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJWPA03	| Get-NetworkAdapter -Name 	'Network adapter 3'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $false	 -confirm:$false
Get-VM 	UNIRJWPA03	| Get-NetworkAdapter -Name 	'Network adapter 2'	| Set-NetworkAdapter -NetworkName 	VLAN_1113_PROD_0	-StartConnected	 $true	 -confirm:$false
