New-VM -VMFilePath  '[DS-TS01] UNIRJTS09/UNIRJTS09.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS01/UNIRJTS01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTSMX01/UNIRJTSMX01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS22/UNIRJTS22.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS02/UNIRJTS02.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS06/UNIRJTS06.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS05/UNIRJTS05.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS20/UNIRJTS20.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTSAB01/UNIRJTSAB01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS07/UNIRJTS07.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS03/UNIRJTS03.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTSAUT01/UNIRJTSAUT01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS21/UNIRJTS21.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS23/UNIRJTS23.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS01] UNIRJTS08/UNIRJTS08.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTSWPD06/UNIRJTSWPD06.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS11/UNIRJTS11.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTSINT01/UNIRJTSINT01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS10/UNIRJTS10.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS18/UNIRJTS18.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS12_Clone/UNIRJTS12_Clone.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS15/UNIRJTS15.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTSAB02/UNIRJTSAB02.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTSMX02/UNIRJTSMX02.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS19/UNIRJTS19.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS16/UNIRJTS16.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS13/UNIRJTS13.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS24/UNIRJTS24.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS17/UNIRJTS17.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-TS02] UNIRJTS14/UNIRJTS14.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-EXC02] MBXSRV12/MBXSRV12.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-EXC02] CASSRV14/CASSRV14.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-EXC01] UNIRJMBX01/UNIRJMBX01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-EXC01] CASSRV13/CASSRV13.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP02] UNIRJTLN07/UNIRJTLN07.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP02] UNIRJTLN05/UNIRJTLN05.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP02] PIXEON-VA/PIXEON-VA.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP02] DNSSRV25/DNSSRV25.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP02] UNIRJWPA03/UNIRJWPA03.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP01] UNIRJTLN01/UNIRJTLN01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP01] UNIRJTLN04/UNIRJTLN04.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP01] UNIRJWBI01.UREMH.local/UNIRJWBI01.UREMH.local.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP01] UNIRJTLN06/UNIRJTLN06.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-APP01] DNSSRV24/DNSSRV24.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[DS-FS] UNIRJFS01/UNIRJFS01.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync
New-VM -VMFilePath  '[URJ-DS-REPLICA_LUN_471] UNIRJDB11/UNIRJDB11.vmx'  -VMHost $ESXHost -Location $VMFolder -RunAsync